import 'package:flutter/material.dart';
import 'package:flutter_meragi_design/src/theme/theme_tokens.dart';

ThemeToken light = ThemeToken(
  filledStandardButtonColor: Colors.deepPurple[100]!,
  filledPrimaryButtonColor: Colors.deepPurple,
  filledSecondaryButtonColor: Colors.deepPurpleAccent[100]!,
  filledDangerButtonColor: Colors.redAccent,
  filledInfoButtonColor: Colors.blue,
  filledWarningButtonColor: Colors.redAccent[100]!,
  outlineBackgroundColor: Colors.white,
  outlineStandardBorderButtonColor: Colors.grey[500]!,
  outlinePrimaryBorderButtonColor: Colors.deepPurple,
  outlineSecondaryBorderButtonColor: Colors.deepPurpleAccent[100]!,
  outlineDangerBorderButtonColor: Colors.redAccent,
  outlineInfoBorderButtonColor: Colors.blue,
  outlineWarningBorderButtonColor: Colors.redAccent[100]!,
  smButtonHeight: 34,
  smButtonPadding: const EdgeInsets.symmetric(horizontal: 12),
  rgButtonHeight: 42,
  rgButtonPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 0),
  lgButtonHeight: 50,
  lgButtonPadding: const EdgeInsets.symmetric(horizontal: 32, vertical: 0),
  smBorderRadius: 4,
  rgBorderRadius: 6,
  lgBorderRadius: 8,
  smButtonIconSize: 14,
  rgButtonIconSize: 16,
  lgButtonIconSize: 18,
  filledStandardButtonIconColor: Colors.white,
  filledPrimaryButtonIconColor: Colors.white,
  filledSecondaryButtonIconColor: Colors.white,
  filledInfoButtonIconColor: Colors.white,
  filledWarningButtonIconColor: Colors.white,
  filledDangerButtonIconColor: Colors.white,
  ghostStandardButtonIconColor: Colors.deepPurple[100]!,
  ghostPrimaryButtonIconColor: Colors.deepPurple,
  ghostSecondaryButtonIconColor: Colors.deepPurpleAccent[100]!,
  ghostInfoButtonIconColor: Colors.blue,
  ghostWarningButtonIconColor: Colors.redAccent,
  ghostDangerButtonIconColor: Colors.redAccent[100]!,

  filledDisabledButtonColor: Colors.grey[200]!,
  ghostDisabledButtonColor: Colors.grey[200]!,
  outlinedDisabledButtonColor: Colors.grey[200]!,
  outlinedDisabledBorderButtonColor: Colors.grey[300]!,
  disabledIconButtonColor: Colors.grey[400]!,

  smButtonTextStyle: const TextStyle(
    fontSize: 12,
    height: 1.5,
    fontWeight: FontWeight.w400,
  ),
  rgButtonTextStyle:  const TextStyle(
    fontSize: 14,
    height: 1.5,
    fontWeight: FontWeight.w500,
  ),
  lgButtonTextStyle:  const TextStyle(
    fontSize: 16,
    height: 1.5,
    fontWeight: FontWeight.w500,
  ),
  filledStandardHoverButtonColor: Colors.deepPurple[100]!.withOpacity(0.7),
  filledPrimaryHoverButtonColor: Colors.deepPurple.withOpacity(0.7),
  filledSecondaryHoverButtonColor: Colors.deepPurpleAccent[100]!.withOpacity(0.7),
  filledWarningHoverButtonColor: Colors.redAccent[100]!.withOpacity(0.7),
  filledDangerHoverButtonColor: Colors.redAccent.withOpacity(0.7),
  filledInfoHoverButtonColor: Colors.blue.withOpacity(0.7),

  outlineStandardHoverButtonColor: Colors.deepPurple[100]!.withOpacity(0.3),
  outlinePrimaryHoverButtonColor: Colors.deepPurple.withOpacity(0.3),
  outlineSecondaryHoverButtonColor: Colors.deepPurpleAccent[100]!.withOpacity(0.3),
  outlineWarningHoverButtonColor: Colors.redAccent[100]!.withOpacity(0.3),
  outlineDangerHoverButtonColor: Colors.redAccent.withOpacity(0.3),
  outlineInfoHoverButtonColor: Colors.blue.withOpacity(0.3),

  ghostStandardHoverButtonColor: Colors.deepPurple[100]!.withOpacity(0.3),
  ghostPrimaryHoverButtonColor: Colors.deepPurple.withOpacity(0.3),
  ghostSecondaryHoverButtonColor: Colors.deepPurpleAccent[100]!.withOpacity(0.3),
  ghostWarningHoverButtonColor: Colors.redAccent[100]!.withOpacity(0.3),
  ghostDangerHoverButtonColor: Colors.redAccent.withOpacity(0.3),
  ghostInfoHoverButtonColor: Colors.blue.withOpacity(0.3),
);
